version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env
  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    env_file:
      - ./.env
    ports:
      - "5050:80"
volumes:
  postgres_db:
